name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs every day at midnight
  workflow_dispatch: # Manual trigger
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Classic Metrics (Main Widget)
        uses: lowlighter/metrics@latest
        with:
          user: Anurag1428
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          template: classic
          config_timezone: Asia/Kolkata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used, recently-used
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 500

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes

          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 15

          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 3
          plugin_anilist_user: Anurag1428

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_charts: yes
          plugin_habits_facts: yes

          committer_token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          filename: metrics.svg
          gist: ${{ secrets.METRICS_GIST }}

      - name: Terminal Theme (Languages Widget)
        uses: lowlighter/metrics@latest
        with:
          user: Anurag1428
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          template: terminal
          config_timezone: Asia/Kolkata

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 500

          committer_token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          filename: metrics.languages.svg
          gist: ${{ secrets.METRICS_GIST }}

      - name: Minimalist Achievements
        uses: lowlighter/metrics@latest
        with:
          user: Anurag1428
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          template: classic
          config_padding: 0, 8 + 0, 8
          config_output: svg
          config_twemoji: yes
          config_timezone: Asia/Kolkata
          
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: B

          committer_token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          filename: metrics.achievements.svg
          gist: ${{ secrets.METRICS_GIST }}

      - name: Anime & Music Focused
        uses: lowlighter/metrics@latest
        with:
          user: Anurag1428
          token: ${{ secrets.METRICS_TOKEN }}
          template: anime
          config_timezone: Asia/Kolkata
          
          plugin_anilist: yes
          plugin_anilist_user: Anurag1428
          plugin_anilist_sections: favorites
          plugin_anilist_limit: 3

          plugin_music: no # Enable if you want, needs LASTFM_API_KEY
          # plugin_music_provider: lastfm
          # plugin_music_token: ${{ secrets.LASTFM_API_KEY }}
          # plugin_music_limit: 5
          # plugin_music_played_at: yes
          # plugin_music_top_type: tracks

          committer_token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          filename: metrics.anime.svg
          gist: ${{ secrets.METRICS_GIST }}
