name: Metrics

on:
  schedule:
    - cron: "0 18 * * *" # Runs daily at midnight IST
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      # ===============================
      # BASE HEADER + REPOS (GENERAL)
      # ===============================
      - name: Metrics (General Overview)
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_gist: ${{ secrets.GIST_ID }}
          output_action: gist
          config_timezone: Asia/Kolkata

          base: header, repositories
          base_indepth: yes

          # plugin_isocalendar: yes
          # plugin_isocalendar_duration: full-year
          plugin_isocalendar: yes
          plugin_isocalendar_sections: half-year
          plugin_isocalendar_as: 3d
          plugin_isocalendar_size: large
          plugin_isocalendar_saturation: 1
          plugin_isocalendar_colors: "0:000000, 0.25:008000, 0.5:00FF00, 1:ADFF2F"


          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_indepth: yes

          config_display: large
          config_padding: 10
          config_gemoji: yes
          config_animations: yes
          config_twemoji: no
          config_octicon: no

      # ===============================
      # ANILIST WIDGET
      # ===============================
      - name: Metrics (Anilist)
        uses: lowlighter/metrics@latest
        with:
          filename: anilist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_gist: ${{ secrets.GIST_ID }}
          output_action: gist
          config_timezone: Asia/Kolkata

          plugin_anilist: yes
          plugin_anilist_user: Progami
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters, watching
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22

          config_display: large
          config_order: anilist
          config_padding: 10
          config_gemoji: yes
          config_animations: yes

      # ===============================
      # ACHIEVEMENTS WIDGET
      # ===============================
      - name: Metrics (Achievements)
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_gist: ${{ secrets.GIST_ID }}
          output_action: gist
          config_timezone: Asia/Kolkata

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 10

          config_display: large
          config_padding: 10
          config_gemoji: yes
          config_animations: yes

      # ===============================
      # MUSIC WIDGET (Spotify)
      # ===============================
      - name: Metrics (Spotify Music)
        uses: lowlighter/metrics@latest
        with:
          filename: music.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_gist: ${{ secrets.GIST_ID }}
          output_action: gist
          config_timezone: Asia/Kolkata

          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
          plugin_music_refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          plugin_music_mode: recent
          plugin_music_limit: 9
          plugin_music_played_at: yes
          plugin_music_user: anurag1428

          config_display: large
          config_padding: 10
          config_gemoji: yes
          config_animations: yes

      # ===============================
      # NOTABLE CONTRIBUTIONS
      # ===============================
      - name: Metrics (Notable Contributions)
        uses: lowlighter/metrics@latest
        with:
          filename: notable.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_gist: ${{ secrets.GIST_ID }}
          output_action: gist
          config_timezone: Asia/Kolkata

          plugin_notable: yes
          plugin_notable_filter: stars:>0

          config_display: large
          config_padding: 10
          config_gemoji: yes
          config_animations: yes

      # ===============================
      # STARGAZERS
      # ===============================
      - name: Metrics (Stargazers)
        uses: lowlighter/metrics@latest
        with:
          filename: stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_gist: ${{ secrets.GIST_ID }}
          output_action: gist
          config_timezone: Asia/Kolkata

          plugin_stargazers: yes
          plugin_stargazers_charts: true
          plugin_stargazers_charts_type: classic

          config_display: large
          config_padding: 10
          config_gemoji: yes
          config_animations: yes

      # ===============================
      # FORTUNE (Quotes)
      # ===============================
      - name: Metrics (Fortune Quotes)
        uses: lowlighter/metrics@latest
        with:
          filename: fortune.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_gist: ${{ secrets.GIST_ID }}
          output_action: gist
          config_timezone: Asia/Kolkata

          plugin_fortune: yes

          config_display: large
          config_padding: 10
          config_gemoji: yes
          config_animations: yes
