name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]  # Every day at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          # GitHub token with public_repo and read:user (default is fine for public data)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options (choose what you want to display!)
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: bytes-size, percentage
