name: Metrics

on:
  # Runs automatically every day at midnight IST (18:30 UTC)
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch: # Manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Metrics (General + Languages + Achievements + Anilist + Spotify)
        uses: lowlighter/metrics@latest
        with:
          # MAIN SETTINGS
          token: ${{ secrets.METRICS_TOKEN }}        # GitHub PAT with repo + gist
          committer_gist: ${{ secrets.GIST_ID }}      # Gist ID for output
          output_action: gist                         # Output to Gist
          config_timezone: Asia/Kolkata               # Your timezone
          
          # BASE HEADER + REPO ACTIVITY
          base: header, repositories
          base_indepth: yes
          
          # ISOCALENDAR (Contributions)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # LANGUAGES STATS
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 8

          # ACHIEVEMENTS
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 10

          # ANILIST (Anime)
          plugin_anilist: yes
          plugin_anilist_token: ${{ secrets.ANILIST_TOKEN }}
          plugin_anilist_user: Anurag1428
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters, watching
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22

          # SPOTIFY MUSIC
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
          plugin_music_refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          plugin_music_mode: recent
          plugin_music_limit: 9
          
          # GITHUB TOPICS
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 15

          # REPO NOTABLES
          plugin_notable: yes
          plugin_notable_filter: stars:>0
          
          # STARGAZERS
          plugin_stargazers: yes

          # FOLLOW-UP QUOTES (Fortune)
          plugin_fortune: yes

          # CUSTOMIZATION (Themes and Layout)
          config_order: base.header, isocalendar, languages, notable, anilist, music, achievements
          config_display: large
          config_padding: 10
          config_title: 👾 Anurag1428 👾
