name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * *" }] # Runs daily at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Anurag1428
          template: classic
          config_timezone: Asia/Kolkata

          config_theme: terminal
          config_order: base, isocalendar, languages, habits, topics, achievements, stars, pagespeed, music, anilist
          config_twemoji: yes
          config_padding: 0, 8 + 11%

          base: header, activity, community, repositories, metadata

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage, bytes-size
          plugin_languages_limit: 8
          plugin_languages_indepth: yes

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes

          plugin_stars: yes
          plugin_stars_limit: 4

          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 15

          plugin_pagespeed: yes
          plugin_pagespeed_url: https://starter-pack-iota.vercel.app/
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_pwa: yes

          plugin_music: yes
          plugin_music_provider: anilist
          plugin_music_limit: 4
          plugin_music_user: Anurag1428

          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching, characters
          plugin_anilist_limit: 2
