name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]  # Runs every day at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Base Metrics - Classic
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Anurag1428
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used, recently-used
          plugin_topics: yes
          plugin_achievements: yes
          plugin_music: yes
          plugin_stars: yes

      - name: Anime - Naruto Theme
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-anime-naruto.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Anurag1428
          template: classic
          base: anime
          config_order: anime
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters, watching, reading
          plugin_anilist_limit: 4
          config_twemoji: yes
          config_octicon: yes
          config_timezone: Asia/Kolkata

      - name: Minimal Theme
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-minimal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Anurag1428
          template: minimal
          base: header, repositories
          config_timezone: Asia/Kolkata
          plugin_isocalendar: yes

      - name: Achievements with Terminal Theme
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics-terminal-achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Anurag1428
          template: terminal
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          config_timezone: Asia/Kolkata
