name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]  # Runs every day at midnight
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # General settings
          user: Anurag1428
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # ➤ 1. Coding habits (time/day/language)
          plugin_habits: yes
          plugin_habits_from: 200         # Analyze last 200 events
          plugin_habits_days: 14          # From last 14 days
          plugin_habits_facts: yes        # Show cool facts
          plugin_habits_charts: yes       # Show charts (time/day)

          # ➤ 2. Isometric contributions calendar (3D)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year  # Last 6 months

          # ➤ 3. Languages used
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_indepth: yes

          # ➤ 4. PageSpeed Insights
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://starter-pack-iota.vercel.app/  # Your portfolio URL
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_pwa: yes

          # ➤ 5. Topics (mastered technologies)
          plugin_topics: yes
          plugin_topics_mode: mastered    # Show mastered topics
          plugin_topics_limit: 15         # Show up to 15 topics

          # ➤ 6. Music (Apple Music or Spotify)
          plugin_music: yes
          plugin_music_provider: apple
          plugin_music_playlist: 908653514  # Your Apple Music playlist ID (or remove this)
          plugin_music_limit: 4
          plugin_music_played_at: yes
          plugin_music_user: YOUR_APPLE_ID # Optional, if you want it customized

          # ➤ 7. Achievements (optional)
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          # ➤ 8. Stars received history (optional)
          plugin_stars: yes
          plugin_stars_limit: 4
